### ISSUE TITLE
api-dev still does not have correct meeting intervals.

### ISSUE THREAD

**Issue by RaphaelArkadyMeyer** [Purdue-io/PurdueApi#19]
If you query /odata/Meetings on api-dev.purdue.io, then we see that the meeting length is always zero. Is it possible that the data needs to be downloaded again so that the index error in the parsing utility can be accounted for?

**Comment by haydenmc** [comment]
Apologies – have yet to run a CatalogSync on the dev instance. Will do shortly.

Sent from my Windows 10 phone

**Comment by haydenmc** [comment]
Looks like this change introduces a problem with parsing. Investigating further.

**Comment by haydenmc** [comment]
I've committed a change to the dev instance that should address this - CatalogSync is running now. Can you confirm that the dev instance is showing the appropriate data? Then I can deploy to master.

Thanks!

**Comment by RaphaelArkadyMeyer** [comment]
I'm afraid that the dev instance is still not showing a correct output still. Consider this [sample output](https://api-dev.purdue.io/odata/Meetings/?$filter=MeetingClusterId%20le%203) directly from api-dev. The duration fields all show `PT0S`, which corresponds to zero seconds. I don't believe that any course meetings are zero seconds in length, and tests with much larger inputs show the same output. Either the dev instance is not properly using the dev branch code, or the fix I provided did not resolve the issue at hand.

**Comment by haydenmc** [comment]
Your sample output is courses from Spring 2012, which CatalogSync is not updating (due to it being an old term). If you look to Spring 2017, are you seeing the data you're expecting?

Keep in mind many sections _do_ have 0 duration due to being an independent study, research, etc. You can look the section up on MyPurdue to confirm.

**Comment by RaphaelArkadyMeyer** [comment]
Many courses now have meeting duration as expected, but not all. I also stand corrected about the duration in some cases, but if you look at [this query](http://api-dev.purdue.io/odata/Meetings/?$filter=MeetingClusterId%20eq%20205913), we still see `PT0S` for a lab section of CS180 that is an hour an fifty minutes long during spring 2017. The problem appears to be partially fixed.

**Comment by haydenmc** [comment]
Looking into this... your previous PR actually revealed some issues with how meeting changes are handled in CatalogSync, which I [attempted to fix](https://github.com/Purdue-io/PurdueApi/commit/5b893f7b0ec850de9360a8f44e4299c60f861fea).

**Comment by haydenmc** [comment]
In fact, it looks like the section the meeting in your example belongs to no longer exists on MyPurdue when I manually search for it. This explains why the duration is still zero - but also reveals a problem with invalidating outdated/removed course information.
